
name: 'random-cron'

on:
  #schedule:
    #- cron: '0 0 */17 * *'
  # 点击star时触发运行
  #watch:
    #types: started
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Random Cron
        uses: grbnb/random-workflow-cron@main
        with:
          #ref_branch: main
          #author: ${{ secrets.AUTHOR }}
          github_token: ${{ secrets.PAT }}
          keep_history: true
          time_zone: "UTC+8"
          hour_start: 0
          hour_end: 21
          interval_count: 7
          cron_dmw: "*/15 * *"

        
        
        

